AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sampleapp_1
  Sample SAM Template for sampleapp_1

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET, POST, OPTION'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"   

# sam deploy --parameter-overrides EmailAddress=your-email@example.com
Parameters:
  EmailAddress:
    Type: String
    Description: SNS Topic Email Subscription
    NoEcho: true

Resources:
  MyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "MyPortfolioContactTopic"

  MyContactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: contact/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /contact
            Method: post
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MyNotificationTopic
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MyNotificationTopic.TopicName

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailAddress
      Protocol: "email"
      TopicArn: !Ref MyNotificationTopic

  MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "portfolio-site-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MyOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "MyPortfolioOAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html        
        Origins:
          - Id: MyS3Origin
            DomainName: !GetAtt MyWebsiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt MyOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""

        DefaultCacheBehavior:
          TargetOriginId: MyS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${MyWebsiteBucket.Arn}/*" # バケット内の全ファイル
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${MyDistribution}

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for contact function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/contact/"

  PortfolioUrl:
      Description: "URL for website hosted on CloudFront"
      Value: !Sub "https://${MyDistribution.DomainName}"
